CC = cc
CFLAGS =

BUILD_DIR = $(shell pwd)

objects = scanner.o
include_directories = private/ include/
CFLAGS += $(foreach dir,$(include_directories),-I$(BUILD_DIR)/$(dir))

all: vaq-make

vaq-make: $(objects)
	$(CC) $(CFLAGS) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@

clean:
	rm -f $(objects) vaq-make
